config/routes.rb
SrecTrading::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: :index

  resources :brokers do
    delete 'destroy_multiple', on: :collection
  end

  resources :counterparties do
    delete 'destroy_multiple', on: :collection
  end

  resources :price_buckets do
    delete 'destroy_multiple', on: :collection
  end

  resources :payment_method_overrides do
    delete 'destroy_multiple', on: :collection
  end

  root :to => 'dashboard#index'
end

app/controllers/price_buckets_controller.rb
class PriceBucketsController < ApplicationController
  add_breadcrumb I18n.t('dashboard'), :root_path
  add_breadcrumb I18n.t('clearing_price_buckets_model'), :price_buckets_path

  def index
    @price_buckets = ClearingPriceBucket.order('created_at DESC')
  end

  def new
    @price_bucket = ClearingPriceBucket.new

    add_breadcrumb I18n.t('clearing_price_buckets.new')
  end

  def show
    @price_bucket = ClearingPriceBucket.find(params[:id])

    add_breadcrumb @price_bucket.name
  end

  def edit
    @price_bucket = ClearingPriceBucket.find(params[:id])

    add_breadcrumb @price_bucket.name, price_bucket_path(@price_bucket)
    add_breadcrumb I18n.t('edit')
  end

  def create
    @price_bucket = ClearingPriceBucket.new(params[:clearing_price_bucket])

    if @price_bucket.save
      redirect_to price_buckets_path, notice: "New '#{@price_bucket.name}' bucket was successfully created."
    else
      render :new
    end
  end

  def update
    @price_bucket = ClearingPriceBucket.find(params[:id])

    if @price_bucket.update_attributes(params[:clearing_price_bucket])
      redirect_to price_bucket_path(@price_bucket), notice: "Clearing Price Bucket '#{@price_bucket.name}' was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @price_bucket = ClearingPriceBucket.find(params[:id]).destroy
    redirect_to price_buckets_path, notice: "Clearing Price Bucket '#{@price_bucket.name}' was successfully deleted."
  end

  def destroy_multiple
    if params[:clearing_price_buckets].present?
      ClearingPriceBucket.destroy(params[:clearing_price_buckets])
      redirect_to price_buckets_path, notice: "Clearing Price Buckets with id #{params[:clearing_price_buckets].join(',')} was successfully deleted."
    else
      redirect_to price_buckets_path, alert: 'No clearing price buckets was selected'
    end
  end
end

app/views/price_buckets/_form.html.slim
= simple_form_for @price_bucket, url: path, html: { class: 'form-vertical' } do |f|
  - if @price_bucket.errors.any?
    .alert.alert-danger
      h4
        = pluralize(@price_bucket.errors.count, "error")
        = t('clearing_price_buckets.form_error_message')
      ul
        - @price_bucket.errors.full_messages.each do |msg|
          li= msg

  = f.input :name
  = f.input :description, input_html: { rows: 8 }
  = f.association :applicable_state, collection: State.all, :label => t('clearing_price_buckets.applicable_state')

  .form-actions
    = link_to t('cancel'), price_buckets_path, class: :btn
    = f.submit t('save'), class: 'btn btn-primary'

app/views/price_buckets/edit.html.slim
.sidebar
.col-md-4
  = render 'form', path: price_bucket_path(@price_bucket)

app/views/price_buckets/index.html.slim
= form_tag destroy_multiple_price_buckets_path, method: :delete do
  .sidebar
    ul.nav.nav-sidebar
      li
        p.text-left = link_to t('clearing_price_buckets.create_new'), new_price_bucket_path, class: 'btn btn-primary'
      li
        = submit_tag t('clearing_price_buckets.delete_selected'), class: 'btn btn-danger', data: { confirm: t('delete_confirm') }
  .content-area
    p.lead = t('clearing_price_buckets_model')
    table.table.table-hover.table-bordered
      thead
        tr
          th
          th = t('clearing_price_buckets.id')
          th = t('clearing_price_buckets.name')
          th = t('clearing_price_buckets.description')
          th = t('clearing_price_buckets.applicable_state')
          th
      tbody
        - @price_buckets.each do |price_bucket|
          tr
            td = check_box_tag "clearing_price_buckets[]", price_bucket.id
            td = price_bucket.id
            td = price_bucket.name
            td = price_bucket.description
            td = price_bucket.applicable_state.abbreviation if price_bucket.applicable_state.present?
            td
              = link_to t('view'), price_bucket_path(price_bucket), :class => 'btn btn-xs btn-info'
              | &nbsp;
              = link_to t('edit'), edit_price_bucket_path(price_bucket), :class => 'btn btn-xs btn-success'

app/views/price_buckets/new.html.slim
.sidebar
.col-md-4
  = render 'form', :path => price_buckets_path

app/views/price_buckets/show.html.slim
.sidebar
  ul.nav.nav-sidebar
    li
      = link_to t('clearing_price_buckets.edit'), edit_price_bucket_path(@price_bucket)
    li
      = link_to t('clearing_price_buckets.delete'), price_bucket_path(@price_bucket), method: :delete, data: { confirm: t('delete_confirm') }
.col-md-4
  p.lead = t('clearing_price_buckets.view_bucket_name', name: @price_bucket.name)

  table.table.well
    tbody
      tr
        td
          b = t('clearing_price_buckets.name')
        td = @price_bucket.name
      tr
        td
          b = t('clearing_price_buckets.description')
        td = @price_bucket.description
      tr
        td
          b = t('clearing_price_buckets.applicable_state')
        td = @price_bucket.applicable_state.abbreviation if @price_bucket.applicable_state.present?