config/routes.rb
SrecTrading::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: :index

  resources :brokers do
    delete 'destroy_multiple', on: :collection
  end

  resources :counterparties do
    delete 'destroy_multiple', on: :collection
  end

  resources :price_buckets do
    delete 'destroy_multiple', on: :collection
  end

  resources :payment_method_overrides do
    delete 'destroy_multiple', on: :collection
  end

  root :to => 'dashboard#index'
end

app/models/payment_method_override.rb
class PaymentMethodOverride < ActiveRecord::Base
  extend Enumerize

  attr_accessible :name, :description, :payment_method, :payment_frequency, :fixed_customer_payment, :brokerage_customer_percentage, :per_acp_customer_percentage, :per_acp_acp_schedule_id

  validates :name, :payment_method, :payment_frequency, presence: true
  validates :brokerage_customer_percentage, :per_acp_customer_percentage, :inclusion => 0..1, allow_blank: true

  enumerize :payment_method, in: [:fixed, :per_acp, :brokerage, :spot]
  enumerize :payment_frequency, in: [:annually, :semiannually, :quarterly, :never]

  belongs_to :per_acp_acp_schedule, class_name: 'AcpSchedule'
end

app/controllers/payment_method_overrides_controller.rb
class PaymentMethodOverridesController < ApplicationController
  add_breadcrumb I18n.t('dashboard'), :root_path
  add_breadcrumb I18n.t('payment_method_overrides_model'), :payment_method_overrides_path

  def index
    @payment_method_overrides = PaymentMethodOverride.order('created_at DESC')
  end

  def new
    @payment_method_override = PaymentMethodOverride.new

    add_breadcrumb I18n.t('payment_method_overrides.new')
  end

  def show
    @payment_method_override = PaymentMethodOverride.find(params[:id])

    add_breadcrumb @payment_method_override.name
  end

  def edit
    @payment_method_override = PaymentMethodOverride.find(params[:id])

    add_breadcrumb @payment_method_override.name, payment_method_override_path(@payment_method_override)
    add_breadcrumb I18n.t('edit')
  end

  def create
    @payment_method_override = PaymentMethodOverride.new(params[:payment_method_override])

    if @payment_method_override.save
      redirect_to payment_method_overrides_path, notice: "#{@payment_method_override.name} was successfully created."
    else
      render :new
    end
  end

  def update
    @payment_method_override = PaymentMethodOverride.find(params[:id])

    if @payment_method_override.update_attributes(params[:payment_method_override])
      redirect_to payment_method_override_path(@payment_method_override), notice: "#{@payment_method_override.name} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @payment_method_override = PaymentMethodOverride.find(params[:id]).destroy
    redirect_to payment_method_overrides_path, notice: "#{@payment_method_override.name} was successfully deleted."
  end

  def destroy_multiple
    if params[:payment_method_overrides].present?
      PaymentMethodOverride.destroy(params[:payment_method_overrides])
      redirect_to payment_method_overrides_path, notice: "Payment method overrides with id #{params[:payment_method_overrides].join(',')} was successfully deleted."
    else
      redirect_to payment_method_overrides_path, alert: 'No Payment method override was selected'
    end
  end
end

app/views/payment_method_overrides/_form.html.slim
= simple_form_for @payment_method_override, html: { class: 'form-vertical' } do |f|
  - if @payment_method_override.errors.any?
    .alert.alert-danger
      h4
        = pluralize(@payment_method_override.errors.count, "error")
        = t('payment_method_overrides.form_error_message')
      ul
        - @payment_method_override.errors.full_messages.each do |msg|
          li= msg

  = f.input :name
  = f.input :description, input_html: { rows: 8 }
  = f.input :payment_method
  = f.input :payment_frequency
  = f.input :brokerage_customer_percentage
  = f.input :fixed_customer_payment
  = f.input :per_acp_customer_percentage
  = f.association :per_acp_acp_schedule, collection: AcpSchedule.all, :label => t('payment_method_overrides.per_acp_acp_schedule_id')

  .form-actions
    = link_to t('cancel'), payment_method_overrides_path, class: :btn
    = f.submit t('save'), class: 'btn btn-primary'

app/views/payment_method_overrides/edit.html.slim
.sidebar
.col-md-4
  = render 'form'

app/views/payment_method_overrides/index.html.slim
= form_tag destroy_multiple_payment_method_overrides_path, method: :delete do
  .sidebar
    ul.nav.nav-sidebar
      li
        p.text-left = link_to t('payment_method_overrides.create_new'), new_payment_method_override_path, class: 'btn btn-primary'
      li
        = submit_tag t('payment_method_overrides.delete_selected'), class: 'btn btn-danger', data: { confirm: t('delete_confirm') }
  .content-area
    p.lead = t('payment_method_overrides_model')
    table.table.table-hover.table-bordered
      thead
        tr
          th
          th = t('payment_method_overrides.id')
          th = t('payment_method_overrides.name')
          th = t('payment_method_overrides.payment_method')
          th = t('payment_method_overrides.payment_frequency')
          th = t('payment_method_overrides.description')
          th
      tbody
        - @payment_method_overrides.each do |payment_method_override|
          tr
            td = check_box_tag "payment_method_overrides[]", payment_method_override.id
            td = payment_method_override.id
            td = payment_method_override.name
            td = payment_method_override.payment_method_text
            td = payment_method_override.payment_frequency_text
            td = payment_method_override.description
            td
              = link_to t('view'), payment_method_override_path(payment_method_override), :class => 'btn btn-xs btn-info'
              | &nbsp;
              = link_to t('edit'), edit_payment_method_override_path(payment_method_override), :class => 'btn btn-xs btn-success'

app/views/payment_method_overrides/new.html.slim
.sidebar
.col-md-4
  = render 'form'

app/views/payment_method_overrides/show.html.slim
.sidebar
  ul.nav.nav-sidebar
    li
      = link_to t('payment_method_overrides.edit'), edit_payment_method_override_path(@payment_method_override)
    li
      = link_to t('payment_method_overrides.delete'), payment_method_override_path(@payment_method_override), method: :delete, data: { confirm: t('delete_confirm') }
.col-md-4
  p.lead = t('payment_method_overrides.view_override_name', name: @payment_method_override.name)

  table.table.well
    tbody
      tr
        td
          b = t('payment_method_overrides.name')
        td = @payment_method_override.name
      tr
        td
          b = t('payment_method_overrides.description')
        td = @payment_method_override.description
      tr
        td
          b = t('payment_method_overrides.payment_method')
        td = @payment_method_override.payment_method_text
      tr
        td
          b = t('payment_method_overrides.payment_frequency')
        td = @payment_method_override.payment_frequency_text
      tr
        td
          b = t('payment_method_overrides.brokerage_customer_percentage')
        td = @payment_method_override.brokerage_customer_percentage
      tr
        td
          b = t('payment_method_overrides.fixed_customer_payment')
        td = @payment_method_override.fixed_customer_payment
      tr
        td
          b = t('payment_method_overrides.per_acp_customer_percentage')
        td = @payment_method_override.per_acp_customer_percentage
      tr
        td
          b = t('payment_method_overrides.per_acp_acp_schedule_id')
        td = @payment_method_override.per_acp_acp_schedule.name if @payment_method_override.per_acp_acp_schedule.present?