config/routes.rb
SrecTrading::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: :index

  resources :brokers do
    delete 'destroy_multiple', on: :collection
  end

  resources :counterparties do
    delete 'destroy_multiple', on: :collection
  end

  resources :price_buckets do
    delete 'destroy_multiple', on: :collection
  end

  resources :payment_method_overrides do
    delete 'destroy_multiple', on: :collection
  end

  root :to => 'dashboard#index'
end

app/models/broker.rb
class Broker < ActiveRecord::Base
  attr_accessible :company_name, :contact_name, :contact_email, :contact_address, :contact_phone

  validates :company_name, :contact_name, :contact_email, presence: true
  validates :contact_email, uniqueness: true
  validates :contact_email, format: { with: /\A([a-z0-9\-\_\.\+]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :contact_phone, format: { with: /\A(\(\d{3}\))\s(\d{3}\-\d{4})\z/i }, allow_blank: true
end

app/controllers/brokers_controller.rb
class BrokersController < ApplicationController
  add_breadcrumb I18n.t('dashboard'), :root_path
  add_breadcrumb I18n.t('brokers_model'), :brokers_path

  def index
    @brokers = Broker.order('created_at DESC')
  end

  def new
    @broker = Broker.new

    add_breadcrumb I18n.t('brokers.new')
  end

  def show
    @broker = Broker.find(params[:id])

    add_breadcrumb @broker.company_name
  end

  def edit
    @broker = Broker.find(params[:id])

    add_breadcrumb @broker.company_name, broker_path(@broker)
    add_breadcrumb I18n.t('edit')
  end

  def create
    @broker = Broker.new(params[:broker])

    if @broker.save
      redirect_to brokers_path, notice: "#{@broker.company_name} was successfully created."
    else
      render :new
    end
  end

  def update
    @broker = Broker.find(params[:id])

    if @broker.update_attributes(params[:broker])
      redirect_to broker_path(@broker), notice: "#{@broker.company_name} was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @broker = Broker.find(params[:id]).destroy
    redirect_to brokers_path, notice: "#{@broker.company_name} was successfully deleted."
  end

  def destroy_multiple
    if params[:brokers].present?
      Broker.destroy(params[:brokers])
      redirect_to brokers_path, notice: "Brokers with id #{params[:brokers].join(',')} was successfully deleted."
    else
      redirect_to brokers_path, alert: 'No brokers was selected'
    end
  end
end

app/views/brokers/_form.html.slim
= simple_form_for @broker, :html => { :class => 'form-vertical' } do |f|
  - if @broker.errors.any?
    .alert.alert-danger
      h4
        = pluralize(@broker.errors.count, "error")
        = t('brokers.form_error_message')
      ul
        - @broker.errors.full_messages.each do |msg|
          li= msg

  = f.input :company_name
  = f.input :contact_name
  = f.input :contact_email
  = f.input :contact_phone, placeholder: '(555) 678-0987'
  = f.input :contact_address, as: :text, input_html: { rows: 5 }

  .form-actions
    = link_to t('cancel'), brokers_path, class: :btn
    = f.submit t('save'), class: 'btn btn-primary'

app/views/brokers/edit.html.slim
.sidebar
.col-md-4
  = render 'form'

app/views/brokers/index.html.slim
= form_tag destroy_multiple_brokers_path, method: :delete do
  .sidebar
    ul.nav.nav-sidebar
      li
        p.text-left = link_to t('brokers.create_new'), new_broker_path, class: 'btn btn-primary'
      li
        = submit_tag t('brokers.delete_selected'), class: 'btn btn-danger', data: { confirm: t('delete_confirm') }
  .content-area
    p.lead = t('brokers_model')
    table.table.table-hover.table-bordered
      thead
        tr
          th
          th = t('brokers.id')
          th = t('brokers.company_name')
          th = t('brokers.contact_name')
          th = t('brokers.contact_email')
          th = t('brokers.contact_phone')
          th
      tbody
        - @brokers.each do |broker|
          tr
            td = check_box_tag "brokers[]", broker.id
            td = broker.id
            td = broker.company_name
            td = broker.contact_name
            td = broker.contact_email
            td = broker.contact_phone
            td
              = link_to t('view'), broker_path(broker), :class => 'btn btn-xs btn-info'
              | &nbsp;
              = link_to t('edit'), edit_broker_path(broker), :class => 'btn btn-xs btn-success'

app/views/brokers/new.html.slim
.sidebar
.col-md-4
  = render 'form'

app/views/brokers/show.html.slim
.sidebar
  ul.nav.nav-sidebar
    li
      = link_to t('brokers.edit'), edit_broker_path(@broker)
    li
      = link_to t('brokers.delete'), broker_path(@broker), method: :delete, data: { confirm: t('delete_confirm') }
.col-md-4
  p.lead = t('brokers.view_company_name', company_name: @broker.company_name)

  table.table.well
    tbody
      tr
        td
          b = t('brokers.company_name')
        td = @broker.company_name
      tr
        td
          b = t('brokers.contact_name')
        td = @broker.contact_name
      tr
        td
          b = t('brokers.contact_email')
        td = @broker.contact_email
      tr
        td
          b = t('brokers.contact_phone')
        td = @broker.contact_email
      tr
        td
          b = t('brokers.contact_address')
        td = @broker.contact_address