config/routes.rb
SrecTrading::Application.routes.draw do
  devise_for :users

  resource :dashboard, only: :index

  resources :brokers do
    delete 'destroy_multiple', on: :collection
  end

  resources :counterparties do
    delete 'destroy_multiple', on: :collection
  end

  resources :price_buckets do
    delete 'destroy_multiple', on: :collection
  end

  resources :payment_method_overrides do
    delete 'destroy_multiple', on: :collection
  end

  root :to => 'dashboard#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_notifications.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert class="alert-#{name == :notice ? 'success' : 'danger'}"
      a.close data-dismiss="alert" &#215;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_navbar.html.slim
.navbar.navbar-inverse.navbar-static-top role="navigation"
  .container-fixed
    - if user_signed_in?
      ul.nav.navbar-nav.pull-left
        li.dropdown.active
          = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
            = t('administration')
            b.caret
          ul.dropdown-menu
            li
              = link_to t('dashboard'), root_path
            li
              = link_to t('counterparties_model'), counterparties_path
            li
              = link_to t('brokers_model'), brokers_path
            li
              = link_to t('clearing_price_buckets_model'), price_buckets_path
            li
              = link_to t('payment_method_overrides_model'), payment_method_overrides_path
    .pull-right
      ul.nav.navbar-nav
        - if user_signed_in?
          li
            p.navbar-text
              = t('signed_in_as_username', username: current_user.email)
          li
            = link_to t('my_account'), edit_user_registration_path
          li
            = link_to t('sign_out'), destroy_user_session_path, method: :delete
        - else
          li
            = link_to t('login'), new_user_session_path
          li
            = link_to t('sign_up'), new_user_registration_path